In [1]:
from utils import *
import numpy as np
import os
import cv2

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
def project_vertices(vertices, frame_matrix, image_size):
    # Берём только 3х3 матрицу вращения и 3х1 вектор смещения
    R = frame_matrix[:3, :3]
    T = frame_matrix[:3, 3]
    f = 1.0
    H = np.vstack([R * f, T])

    # Ортографическая проекция
    projected = vertices @ H[:3, :3].T + H[:3, 2]
    projected = projected[:, :2]

    # Масштабируем до размера изображения
    projected -= projected.min(axis=0)
    projected /= projected.max(axis=0)
    projected *= np.array(image_size)[::-1]  # W x H
    return projected


def build_triangle_index_map(mesh, image_size):
    vertices = mesh["vertices"]
    faces = mesh["faces"]
    frame_matrix = mesh["frame_matrix"]
    projected_vertices = project_vertices(vertices, frame_matrix, image_size)
    index_map = np.full(image_size[::-1], -1, dtype=np.int32)  # (H, W)

    for tri_idx, face in enumerate(faces):
        pts = projected_vertices[face].astype(np.int32)
        cv2.fillPoly(index_map, [pts], color=tri_idx)

    return index_map

1. Считываем данные и приводим к единой системе координат

In [3]:
# Размер воксельного пространства
VOXEL_GRID_SIZE = 256
# Размер проекции
image_size = (VOXEL_GRID_SIZE * 2, VOXEL_GRID_SIZE * 2)

In [4]:
# Получим пути к исходным файлам
files = [f for f in os.listdir("data") if f.endswith('.x')]

In [5]:
meshes = []
for f in files:
    print(f)
    filepath = os.path.abspath(f'data\\{f}')
    data = parse_x_file(filepath)

    # Переведём координаты точек из локальной системы координат в систему координат камеры
    data['vertices'] = apply_transformation(data.get('vertices'), data.get('frame_matrix'))
    
    # Предварительная индексация треугольников
    data["index_map"] = build_triangle_index_map(data, image_size)
    meshes.append(data)

teapot_1.x
num_vertices: 200310
num_faces: 379304
num_uvs: 200310
teapot_2.x
num_vertices: 190307
num_faces: 358169
num_uvs: 190307


2. Инициализируем воксельное пространство

In [15]:
# Сбор всех вершин в единую структуру
all_vertices = np.vstack([mesh["vertices"] for mesh in meshes])

In [16]:
# Границы сцены
min_bound = np.min(all_vertices, axis=0)
max_bound = np.max(all_vertices, axis=0)
scene_size = max_bound - min_bound

In [17]:
# Размер одного вокселя
voxel_size = scene_size / VOXEL_GRID_SIZE

In [18]:
# Инициализация скалярного поля и весов
D = np.zeros((VOXEL_GRID_SIZE, VOXEL_GRID_SIZE, VOXEL_GRID_SIZE), dtype=np.float32)
W = np.zeros_like(D)

In [19]:
# Сохраняем параметры для дальнейших преобразований
voxel_space = {
    "min_bound": min_bound,
    "max_bound": max_bound,
    "voxel_size": voxel_size,
    "D": D,
    "W": W,
    "grid_size": VOXEL_GRID_SIZE
}

In [44]:
voxel_space.get('voxel_size')

array([0.81945304, 0.48625126, 0.40774163])

3. Объединяем меши воксельным методом

In [20]:
def compute_triangle_normal(p0, p1, p2):
    return np.cross(p1 - p0, p2 - p0)


def point_to_triangle_distance(p, a, b, c):
    # Проекция на плоскость + знак от нормали
    normal = compute_triangle_normal(a, b, c)
    normal /= np.linalg.norm(normal) + 1e-8
    distance = np.dot(p - a, normal)
    return distance


def compute_weight(p, camera_center, normal):
    direction = camera_center - p
    direction /= np.linalg.norm(direction) + 1e-8
    weight = max(0.0, np.dot(direction, normal))
    return weight


def integrate_mesh_to_voxel_grid(mesh, voxel_space):
    vertices = mesh["vertices"]
    faces = mesh["faces"]
    frame_matrix = mesh["frame_matrix"]
    camera_center = frame_matrix[:3, 3]

    D = voxel_space["D"]
    W = voxel_space["W"]
    min_bound = voxel_space["min_bound"]
    voxel_size = voxel_space["voxel_size"]
    grid_size = voxel_space["grid_size"]

    # Попробуем нормализовать координаты вершан и треугольников под размер воксельной сетки
    # До этого большая часть пространства оставалась пустной...
    # Нормализация координат в диапазон [0, GRID_SIZE]
    vertices = (vertices - voxel_space["min_bound"]) / voxel_size

    for face in tqdm(faces, desc="Faces", unit=" triangles", unit_scale=1):
        a, b, c = vertices[face[0]], vertices[face[1]], vertices[face[2]]
        normal = compute_triangle_normal(a, b, c)
        normal /= np.linalg.norm(normal) + 1e-8

        # В каких вокселях лежит треугольник
        tri_min = np.minimum(np.minimum(a, b), c)
        tri_max = np.maximum(np.maximum(a, b), c)
        min_idx = np.floor((tri_min - min_bound) / voxel_size).astype(int)
        max_idx = np.ceil((tri_max - min_bound) / voxel_size).astype(int)
        min_idx = np.clip(min_idx, 0, grid_size - 1)
        max_idx = np.clip(max_idx, 0, grid_size - 1)

        for i in range(min_idx[0], max_idx[0] + 1):
            for j in range(min_idx[1], max_idx[1] + 1):
                for k in range(min_idx[2], max_idx[2] + 1):
                    voxel_center = min_bound + voxel_size * (np.array([i, j, k]) + 0.5)
                    distance = point_to_triangle_distance(voxel_center, a, b, c)
                    weight = compute_weight(voxel_center, camera_center, normal)

                    if weight < 1e-5:
                        continue  # скипаем неинтересные места

                    D[i, j, k] = (W[i, j, k] * D[i, j, k] + weight * distance) / (W[i, j, k] + weight)
                    W[i, j, k] += weight


In [30]:
voxel_space["D"]

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [31]:
voxel_space["W"]

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [23]:
for mesh in meshes:
    integrate_mesh_to_voxel_grid(mesh, voxel_space)

Faces: 100%|██████████| 379k/379k [09:09<00:00, 690 triangles/s]   
Faces: 100%|██████████| 358k/358k [08:59<00:00, 664 triangles/s] 


In [ ]:
len(D[(D == 0) & (W > 0)])

In [ ]:
len(D[W == 0])

In [36]:
# Если дистанция и вес равны 0 — это значит, что воксель не был затронут.
D[W == 0] = np.inf

0

2. Объединяем меши в одну вокселную структуру

In [ ]:
# Чтобы получить больше информации о процессе объединения мешей
o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)

In [ ]:
# Объединяем меши в один PointCloud
pcd, voxel_size = merge_meshes(meshes, VOXEL_GRID_SIZE, mcd_coarse_scale=60, mcd_fine_scale=12, down_sample=True)

In [ ]:
# Посмотрим на результат объединения
o3d.visualization.draw_geometries([pcd])

3. Метод Марширующих кубиков

In [ ]:
voxel_grid, origin, scale = pcd_to_voxel_grid(np.asarray(pcd.points), grid_size=VOXEL_GRID_SIZE, apply_filter=False)

In [ ]:
# Построим меш на воксельной структуре
vertices, faces, normals, values = marching_cubes(voxel_grid, voxel_size, level=0.0000001)
# Переведём координаты в исходный размер
vertices = vertices / (VOXEL_GRID_SIZE - 1) * scale + origin

In [ ]:
# Создадим меш на основе вершин и треугольников
mesh = o3d.geometry.TriangleMesh()
mesh.vertices = o3d.utility.Vector3dVector(vertices)
mesh.triangles = o3d.utility.Vector3iVector(faces)

In [ ]:
# Уберём лишнее если есть
mesh.remove_duplicated_vertices()
mesh.remove_duplicated_vertices()
mesh.remove_unreferenced_vertices()
mesh.remove_non_manifold_edges()
mesh.remove_degenerate_triangles()
mesh.remove_duplicated_triangles()

In [ ]:
# Пересчитаем нормали
mesh.compute_vertex_normals()
mesh.compute_triangle_normals()
mesh.normalize_normals()

In [ ]:
# Посмотрим на результат объединения
o3d.visualization.draw_geometries([mesh])

3.2 Метод Пуассона

In [ ]:
# Построим воксельную структуру из откалиброванных точек всех мешей
voxels, origin, _ = build_voxel_grid(meshes, grid_size=VOXEL_GRID_SIZE)

In [ ]:
# Запустим метод Пуассона
mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd=pcd, depth=9)

In [ ]:
# Убрём шум
vertices_to_remove = densities < np.quantile(densities, 0.02)
mesh.remove_vertices_by_mask(vertices_to_remove)

# Пересчитаем нормали
mesh.compute_vertex_normals()
mesh.compute_triangle_normals()
mesh.normalize_normals()

In [ ]:
# Посмотрим на результат
o3d.visualization.draw_geometries([mesh])

3.3 Метод Альфа-формы (Alpha shapes)

In [ ]:
alpha = voxel_size * 0.8
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha)
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])

4. Сохранение полученного меша

In [ ]:
mesh.triangles

In [ ]:
write_mesh_to_x(mesh, 'output_mesh.x', save_normals=False, save_texture=False)